### ISSUE TITLE
Cannot run in my local computer?

### ISSUE THREAD

**Issue by yjm12321** [sorin-davidoi/storyflow-d3#1]
Hi, all,

I have a question about how to run this code in my local computer. I download the code and open the 

index.html in Chrome, but I cannot select the characters. I guess the program doesn't load the json file. 

What should I do before running the code? Do I need to download any other files to run this code? 

Thanks,

Bigming

**Comment by sorin-davidoi** [comment]
Hi Bigming,

If you open the developer console (Ctrl-Shift-I on Chrome), you will see that browser cannot load the json due to [Cross-Origin XMLHttpRequest policy](https://developer.chrome.com/extensions/xhr). In order to overcome this, you will need to access the site through a web-server.

The simplest way to do this, if you have ```python``` installed, is to run ```python -m http.server``` from the directory ```storyflow-d3``` and then access the site at ```http://localhost:8000/```. A list of simple commands to run static web-servers can be found [here](https://gist.github.com/willurd/5720255).

**Comment by yjm12321** [comment]
Hi sorin-davidoi,

Thank you for your kind help. I solved this problem.

Bigming
